els-ASAP auto commit file/tag libwacom-0.24-1.el7.src.rpm

diff --git a/src/data/Makefile.am b/src/data/Makefile.am
--- a/src/data/Makefile.am
+++ b/src/data/Makefile.am
@@ -1,9 +1,28 @@
 libwacomtabletdir = $(datadir)/libwacom
-dist_libwacomtablet_DATA =  $(shell find $(top_srcdir)/data -name "*.tablet" -printf "%P\n")
+tablet_files = $(shell find $(top_srcdir)/data -name "*.tablet" -printf "%P\n")
+dist_libwacomtablet_DATA =  $(tablet_files)
 
 libwacomstylusdir = $(datadir)/libwacom
-dist_libwacomstylus_DATA =  $(shell find $(top_srcdir)/data -name "*.stylus" -printf "%P\n")
+stylus_files = $(shell find $(top_srcdir)/data -name "*.stylus" -printf "%P\n")
+dist_libwacomstylus_DATA = $(stylus_files)
 
 EXTRA_DIST = wacom.example
 
 SUBDIRS = layouts
+
+check:
+	@for file in $(tablet_files); do \
+		svg=`$(GREP) 'Layout=' "$(top_srcdir)/data/$$file" | $(SED) -e "s/Layout=//"`; \
+		test -z "$$svg" || \
+		test -e "$(top_srcdir)/data/layouts/$$svg" || ( \
+			echo "ERROR: File $$file references nonexistent $$svg" && test); \
+		rc="$$(($$rc + $$?))"; \
+	done && test 0 -eq $$rc;
+	@(export GIT_DIR="$(top_srcdir)/.git"; \
+	 if $(GIT) ls-files >& /dev/null; then \
+		for file in $(tablet_files) $(stylus_files); do \
+			$(GIT) ls-files --error-unmatch "data/$$file" &> /dev/null || ( \
+			echo "ERROR: File $$file is not in git" && test); \
+		rc="$$(($$rc + $$?))"; \
+		done && test 0 -eq $$rc; \
+	fi)
diff --git a/src/data/layouts/Makefile.am b/src/data/layouts/Makefile.am
--- a/src/data/layouts/Makefile.am
+++ b/src/data/layouts/Makefile.am
@@ -1,4 +1,20 @@
 libwacomlayoutsdir = $(datadir)/libwacom/layouts
-dist_libwacomlayouts_DATA =  $(shell find $(top_srcdir)/data/layouts -name "*.svg" -printf "%P\n")
+layouts = $(shell find $(top_srcdir)/data/layouts -name "*.svg" -printf "%P\n")
+dist_libwacomlayouts_DATA =  $(layouts)
 
 EXTRA_DIST = README
+
+check:
+	@for file in $(layouts); do \
+		$(GREP) -q "$$file" $(top_srcdir)/data/*.tablet || (\
+			echo "ERROR: Layout $$file is not referenced" && test); \
+		rc="$$(($$rc + $$?))"; \
+	done && test 0 -eq $$rc;
+	@(export GIT_DIR="$(top_srcdir)/.git"; \
+	if $(GIT) ls-files >& /dev/null; then \
+		for file in $(layouts); do \
+			$(GIT) ls-files --error-unmatch "data/layouts/$$file" &> /dev/null || ( \
+			echo "ERROR: File $$file is not in git" && test); \
+		rc="$$(($$rc + $$?))"; \
+		done && test 0 -eq $$rc; \
+	fi)
